using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace OpenServiceBroker.Instances;

/// <summary>
/// Metadata for a Service Instance.
/// </summary>
public class ServiceInstanceMetadata : IEquatable<ServiceInstanceMetadata>
{
    /// <summary>
    /// Broker specified key-value pairs specifying attributes of Service Instances that are meaningful and relevant to Platform users, but do not directly imply behaviour changes by the Platform.
    /// </summary>
    [JsonProperty("labels", NullValueHandling = NullValueHandling.Ignore)]
    public JObject Labels { get; set; }

    /// <summary>
    /// Broker specific key-value pairs generated by the Service Broker that MAY imply behaviour changes by the Platform. The Platform SHOULD ignore attributes that it does not support.
    /// </summary>
    [JsonProperty("attributes", NullValueHandling = NullValueHandling.Ignore)]
    public JObject Attributes { get; set; }

    public bool Equals(ServiceInstanceMetadata other)
        => other != null
        && JToken.DeepEquals(Labels, other.Labels)
        && JToken.DeepEquals(Attributes, other.Attributes);

    public override bool Equals(object obj) => obj is ServiceInstanceMetadata other && Equals(other);

    public override int GetHashCode()
    {
        unchecked
        {
            return ((Labels?.GetHashCode() ?? 0) * 397) ^ (Attributes?.GetHashCode() ?? 0);
        }
    }
}
